[package]
name = "raweb-api"
version = "0.1.0"
authors = ["Robin Mattheussen <robin.mattheussen@gmail.com>"]
edition = "2018"

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.1.0"
tokio = { version = "0.2.0", features = ["full"] }